server:
  port: 8100
spring:
  application:
    name: payment-service
  cloud:
    nacos:
      discovery:
        server-addr: nacos-nginx:80
  datasource:
    url: jdbc:mysql://sample-mysql:3306/sample-ums?serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  config-location: classpath:mybatis-config.xml
